### ISSUE TITLE
New support for Python in Flow

### ISSUE THREAD

**Issue by deefrawley** [Drimix20/Flow.Launcher.Plugin.DirectTranslate#1]
Hi Drimix20,

Flow can now install an embedded version of python for users, and using a CD pipeline here on Git, can automatically install dependencies relative to an individual plugin so the user needs to just download and run. You do need to make a small adjustment to your plugin to point to where the script looks for libraries, and inlcude the Github Actions script which will run whenever you update the master branch.

Have a look at my plugin repos to see how that works and if you need any assistance just yell out on Discord or GH Discussions

**Comment by Drimix20** [comment]
@deefrawley  Thank you for you suggestion. I will look at it. Currently there is issue in textblob (ref. https://github.com/sloria/TextBlob/issues/395, changed google translate api).
